// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obypgatzhmhpcwzvhlag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ieXBnYXR6aG1ocGN3enZobGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTQyNjksImV4cCI6MjA3MzY3MDI2OX0.lG_T5GmwycZrRkc4bNjsdhjaJ8iBZkOgdqsfSwL3z4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});